name: Lint Docs

on:
  # Trigger the workflow on push or pull request, but only for the main branch.
  # Don't use pull_request.paths filter since this workflow is required for
  # all pull requests on main irrespective of file type or location.
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - "docs/**"

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --frozen --only-group lint
      - name: Lint docs
        run: tools/lint_docs.sh
