# This tests the publication process for vllm-spyre-next by pushing a pre-release
# to test.pypi.org. Only triggers on pre-release tags (e.g. spyre-next-v0.1.0-rc1)
name: Test publication of vllm-spyre-next on test.pypi.org

on:
  push:
    tags:
      - 'spyre-next-v*-rc*'

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/vllm-spyre-next
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4
        with:
            # Fetch all history for setuptools_scm to work correctly
            fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
            version: "latest"
            python-version: "3.12"
      - name: Build package
        run: uv build
        working-directory: vllm_spyre_next
      - name: Publish package distributions to test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            repository-url: https://test.pypi.org/legacy/
            packages-dir: vllm_spyre_next/dist/
